version: "3.4"
services:
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:80"
    command: uvicorn app:app --host 0.0.0.0 --port 80
  frontend:
    image: node:alpine
    container_name: frontend
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /app
    command: ./run.sh
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    tty: true
    depends_on:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
